<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title id="head-title">report.html</title>
      <link href="assets\style.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <h1 id="title">report.html</h1>
    <p>Report generated on 08-Dec-2024 at 00:17:50 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a>
        v4.1.1</p>
    <div id="environment-header">
      <h2>Environment</h2>
    </div>
    <table id="environment"></table>
    <!-- TEMPLATES -->
      <template id="template_environment_row">
      <tr>
        <td></td>
        <td></td>
      </tr>
    </template>
    <template id="template_results-table__body--empty">
      <tbody class="results-table-row">
        <tr id="not-found-message">
          <td colspan="4">No results found. Check the filters.</th>
        </tr>
    </template>
    <template id="template_results-table__tbody">
      <tbody class="results-table-row">
        <tr class="collapsible">
        </tr>
        <tr class="extras-row">
          <td class="extra" colspan="4">
            <div class="extraHTML"></div>
            <div class="media">
              <div class="media-container">
                  <div class="media-container__nav--left"><</div>
                  <div class="media-container__viewport">
                    <img src="" />
                    <video controls>
                      <source src="" type="video/mp4">
                    </video>
                  </div>
                  <div class="media-container__nav--right">></div>
                </div>
                <div class="media__name"></div>
                <div class="media__counter"></div>
            </div>
            <div class="logwrapper">
              <div class="logexpander"></div>
              <div class="log"></div>
            </div>
          </td>
        </tr>
      </tbody>
    </template>
    <!-- END TEMPLATES -->
    <div class="summary">
      <div class="summary__data">
        <h2>Summary</h2>
        <div class="additional-summary prefix">
        </div>
        <p class="run-count">26 tests took 00:47:41.</p>
        <p class="filter">(Un)check the boxes to filter the results.</p>
        <div class="summary__reload">
          <div class="summary__reload__button hidden" onclick="location.reload()">
            <div>There are still tests running. <br />Reload this page to get the latest results!</div>
          </div>
        </div>
        <div class="summary__spacer"></div>
        <div class="controls">
          <div class="filters">
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="failed" />
            <span class="failed">3 Failed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="passed" />
            <span class="passed">23 Passed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="skipped" disabled/>
            <span class="skipped">0 Skipped,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xfailed" disabled/>
            <span class="xfailed">0 Expected failures,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xpassed" disabled/>
            <span class="xpassed">0 Unexpected passes,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="error" />
            <span class="error">2 Errors,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="rerun" disabled/>
            <span class="rerun">0 Reruns</span>
          </div>
          <div class="collapse">
            <button id="show_all_details">Show all details</button>&nbsp;/&nbsp;<button id="hide_all_details">Hide all details</button>
          </div>
        </div>
      </div>
      <div class="additional-summary summary">
      </div>
      <div class="additional-summary postfix">
      </div>
    </div>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable" data-column-type="result">Result</th>
          <th class="sortable" data-column-type="testId">Test</th>
          <th class="sortable" data-column-type="duration">Duration</th>
          <th>Links</th>
        </tr>
      </thead>
    </table>
  </body>
  <footer>
    <div id="data-container" data-jsonblob="{&#34;environment&#34;: {&#34;Python&#34;: &#34;3.9.5&#34;, &#34;Platform&#34;: &#34;Windows-10-10.0.22631-SP0&#34;, &#34;Packages&#34;: {&#34;pytest&#34;: &#34;8.3.3&#34;, &#34;pluggy&#34;: &#34;1.5.0&#34;}, &#34;Plugins&#34;: {&#34;html&#34;: &#34;4.1.1&#34;, &#34;metadata&#34;: &#34;3.1.1&#34;}, &#34;JAVA_HOME&#34;: &#34;C:\\Java\\jdk&#34;}, &#34;tests&#34;: {&#34;ktpm/test_login.py::TestLogin::test_login_valid_info&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Error&#34;, &#34;testId&#34;: &#34;ktpm/test_login.py::TestLogin::test_login_valid_info::setup&#34;, &#34;duration&#34;: &#34;1 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Error&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_login.py::TestLogin::test_login_valid_info::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;1 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;file C:\\Users\\ADMIN\\source\\repos\\OnlineShopDB\\ktpm_selenium\\selenium\\ktpm\\test_login.py, line 5\n      def test_login_valid_info(self, driver):\nE       fixture &amp;#x27;driver&amp;#x27; not found\n&amp;gt;       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, extras, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n&amp;gt;       use &amp;#x27;pytest --fixtures [testpath]&amp;#x27; for help on them.\n\nC:\\Users\\ADMIN\\source\\repos\\OnlineShopDB\\ktpm_selenium\\selenium\\ktpm\\test_login.py:5\n&#34;}], &#34;ktpm/test_payment_gateway.py::TestLogin::test_login_valid_info&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Error&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestLogin::test_login_valid_info::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Error&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestLogin::test_login_valid_info::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;file C:\\Users\\ADMIN\\source\\repos\\OnlineShopDB\\ktpm_selenium\\selenium\\ktpm\\test_login.py, line 5\n      def test_login_valid_info(self, driver):\nE       fixture &amp;#x27;driver&amp;#x27; not found\n&amp;gt;       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, extra, extras, include_metadata_in_junit_xml, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n&amp;gt;       use &amp;#x27;pytest --fixtures [testpath]&amp;#x27; for help on them.\n\nC:\\Users\\ADMIN\\source\\repos\\OnlineShopDB\\ktpm_selenium\\selenium\\ktpm\\test_login.py:5\n&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_not_logged_in&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_not_logged_in&#34;, &#34;duration&#34;: &#34;00:02:18&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_not_logged_in&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:18&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\nAlert accepted successfully!\nYour order is confirmed!\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF5F430&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/3658e211341e6f81f0d3526722164b2a\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF5F700&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/3658e211341e6f81f0d3526722164b2a\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF5F970&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/3658e211341e6f81f0d3526722164b2a&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway&#34;, &#34;duration&#34;: &#34;00:02:21&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:21&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\nAlert accepted successfully!\nYour order is confirmed!\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF5FC40&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/48d0de4f4db8364fe66da8882e984a09\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810008760&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/48d0de4f4db8364fe66da8882e984a09\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF5F760&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/48d0de4f4db8364fe66da8882e984a09&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal&#34;, &#34;duration&#34;: &#34;00:02:20&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:20&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\nDanh s\u00e1ch c\u1eeda s\u1ed5: [&amp;#x27;F063155F1BF7C18541084581E7582F0B&amp;#x27;, &amp;#x27;78E49D4D4FADB8FCDAF8587A1F0F2023&amp;#x27;]\nTi\u00eau \u0111\u1ec1 c\u1eeda s\u1ed5 hi\u1ec7n t\u1ea1i: Log in to your PayPal account\nPh\u1ea7n t\u1eed email input \u0111\u00e3 s\u1eb5n s\u00e0ng.\n\u0110\u00e3 nh\u1ea5n n\u00fat ti\u1ebfp t\u1ee5c.\nPh\u1ea7n t\u1eed password input \u0111\u00e3 s\u1eb5n s\u00e0ng.\n\u0110\u00e3 nh\u1ea5n n\u00fat login.\ncheckout san sang \n\u0110\u00e3 chuy\u1ec3n l\u1ea1i v\u1ec1 c\u1eeda s\u1ed5 g\u1ed1c\nAlert accepted successfully!\nYour order is confirmed!\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF3A250&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/96e8db89070316db05de970129b37413\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80F931F10&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/96e8db89070316db05de970129b37413\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FEFCE50&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/96e8db89070316db05de970129b37413&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_cancel_and_return_checkout&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_cancel_and_return_checkout&#34;, &#34;duration&#34;: &#34;00:01:58&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_cancel_and_return_checkout&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:58&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100081F0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/d0638bffcd3236bfb1a857b6cf62d626\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810008CD0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/d0638bffcd3236bfb1a857b6cf62d626\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810008EE0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/d0638bffcd3236bfb1a857b6cf62d626&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_visa_card&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_visa_card&#34;, &#34;duration&#34;: &#34;00:02:27&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_visa_card&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:27&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\n\u0110\u00e3 chuy\u1ec3n l\u1ea1i v\u1ec1 c\u1eeda s\u1ed5 g\u1ed1c\nAlert accepted successfully!\nYour order is confirmed!\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80F9319D0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/336cfae76d7bdac6c043f6c24f49dc59\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF3A130&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/336cfae76d7bdac6c043f6c24f49dc59\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E80FF3A0A0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/336cfae76d7bdac6c043f6c24f49dc59&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_credit_card&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Failed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_credit_card&#34;, &#34;duration&#34;: &#34;00:01:26&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Failed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_credit_card&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:26&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;self = &amp;lt;ktpm_selenium.selenium.ktpm.test_payment_gateway.TestPaymentGateway_Credit_or_Debit object at 0x000001E80FED4E20&amp;gt;\ndriver = &amp;lt;selenium.webdriver.chrome.webdriver.WebDriver (session=&amp;quot;2a72eb24104b6b81040387d7ec39e877&amp;quot;)&amp;gt;\n\n    def test_paypal_credit_card(self, driver):\n        self.login_and_add_product_to_basket(driver)\n        check_out_page = CheckOutPage(driver)\n    \n        # calculate totals for assert\n        extract_and_calculate_totals = check_out_page.extract_and_calculate_totals(driver)\n        subtotals, shipping, totals, totals_calculated = extract_and_calculate_totals\n    \n        assert totals_calculated == totals, f&amp;quot;Total mismatch: Expected {totals_calculated}, but got {totals}&amp;quot;\n    \n        check_out_page.chose_paypal()\n        time.sleep(1)\n    \n        email_paypal = &amp;quot;sb-wwcid34547417@personal.example.com&amp;quot;\n        password_paypal = &amp;quot;KW.G0FQl&amp;quot;\n        check_out_page.login_paypal(email_paypal, password_paypal)\n        time.sleep(5)\n    \n        totals_paypal = check_out_page.get_totals_paypal()\n        assert totals_calculated == totals_paypal, &amp;quot;ok&amp;quot;\n    \n&amp;gt;       check_out_page.chose_paypal_credit()\n\nktpm\\test_payment_gateway.py:266: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages_derection\\check_out.py:272: in chose_paypal_credit\n    self.scroll_to_element(self.driver.find_element(By.XPATH, &amp;quot;//main/div[2]/section[1]/div[4]/div[4]/div[1]/div/label/span/span&amp;quot;))\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:748: in find_element\n    return self.execute(Command.FIND_ELEMENT, {&amp;quot;using&amp;quot;: by, &amp;quot;value&amp;quot;: value})[&amp;quot;value&amp;quot;]\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = &amp;lt;selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001E810008EE0&amp;gt;\nresponse = {&amp;#x27;status&amp;#x27;: 404, &amp;#x27;value&amp;#x27;: &amp;#x27;{&amp;quot;value&amp;quot;:{&amp;quot;error&amp;quot;:&amp;quot;no such element&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;no such element: Unable to locate element: {\\...07FF6D71DEBB9]\\\\n\\\\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\\\\n\\\\tRtlUserThreadStart [0x00007FF9B638AF38+40]\\\\n&amp;quot;}}&amp;#x27;}\n\n    def check_response(self, response: Dict[str, Any]) -&amp;gt; None:\n        &amp;quot;&amp;quot;&amp;quot;Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        &amp;quot;&amp;quot;&amp;quot;\n        status = response.get(&amp;quot;status&amp;quot;, None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(&amp;quot;message&amp;quot;, &amp;quot;&amp;quot;)\n        screen: str = response.get(&amp;quot;screen&amp;quot;, &amp;quot;&amp;quot;)\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(&amp;quot;value&amp;quot;, None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[&amp;quot;value&amp;quot;]\n                    status = value.get(&amp;quot;error&amp;quot;, None)\n                    if not status:\n                        status = value.get(&amp;quot;status&amp;quot;, ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(&amp;quot;value&amp;quot;) or value.get(&amp;quot;message&amp;quot;)\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(&amp;quot;message&amp;quot;)\n                    else:\n                        message = value.get(&amp;quot;message&amp;quot;, None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(&amp;quot;__&amp;quot;)]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[&amp;quot;value&amp;quot;]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == &amp;quot;&amp;quot; and &amp;quot;message&amp;quot; in value:\n            message = value[&amp;quot;message&amp;quot;]\n    \n        screen = None  # type: ignore[assignment]\n        if &amp;quot;screen&amp;quot; in value:\n            screen = value[&amp;quot;screen&amp;quot;]\n    \n        stacktrace = None\n        st_value = value.get(&amp;quot;stackTrace&amp;quot;) or value.get(&amp;quot;stacktrace&amp;quot;)\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(&amp;quot;\\n&amp;quot;)\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(&amp;quot;lineNumber&amp;quot;, &amp;quot;&amp;quot;)\n                        file = frame.get(&amp;quot;fileName&amp;quot;, &amp;quot;&amp;lt;anonymous&amp;gt;&amp;quot;)\n                        if line:\n                            file = f&amp;quot;{file}:{line}&amp;quot;\n                        meth = frame.get(&amp;quot;methodName&amp;quot;, &amp;quot;&amp;lt;anonymous&amp;gt;&amp;quot;)\n                        if &amp;quot;className&amp;quot; in frame:\n                            meth = f&amp;quot;{frame[&amp;#x27;className&amp;#x27;]}.{meth}&amp;quot;\n                        msg = &amp;quot;    at %s (%s)&amp;quot;\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if &amp;quot;data&amp;quot; in value:\n                alert_text = value[&amp;quot;data&amp;quot;].get(&amp;quot;text&amp;quot;)\n            elif &amp;quot;alert&amp;quot; in value:\n                alert_text = value[&amp;quot;alert&amp;quot;].get(&amp;quot;text&amp;quot;)\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n&amp;gt;       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//main/div[2]/section[1]/div[4]/div[4]/div[1]/div/label/span/span&amp;quot;}\nE         (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF6D7283AF5+28005]\nE       \t(No symbol) [0x00007FF6D71E83F0]\nE       \t(No symbol) [0x00007FF6D708580A]\nE       \t(No symbol) [0x00007FF6D70D5A3E]\nE       \t(No symbol) [0x00007FF6D70D5D2C]\nE       \t(No symbol) [0x00007FF6D711EA97]\nE       \t(No symbol) [0x00007FF6D70FBA7F]\nE       \t(No symbol) [0x00007FF6D711B8B3]\nE       \t(No symbol) [0x00007FF6D70FB7E3]\nE       \t(No symbol) [0x00007FF6D70C75C8]\nE       \t(No symbol) [0x00007FF6D70C8731]\nE       \tGetHandleVerifier [0x00007FF6D757646D+3118813]\nE       \tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\nE       \tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\nE       \tGetHandleVerifier [0x00007FF6D734A44B+841403]\nE       \t(No symbol) [0x00007FF6D71F344F]\nE       \t(No symbol) [0x00007FF6D71EF4C4]\nE       \t(No symbol) [0x00007FF6D71EF65D]\nE       \t(No symbol) [0x00007FF6D71DEBB9]\nE       \tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\nE       \tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException\n\n------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypay_add_debit_credit_card&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Failed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypay_add_debit_credit_card&#34;, &#34;duration&#34;: &#34;00:01:45&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Failed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypay_add_debit_credit_card&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:45&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;self = &amp;lt;ktpm_selenium.selenium.ktpm.test_payment_gateway.TestPaymentGateway_Credit_or_Debit object at 0x000001E80FED4FA0&amp;gt;\ndriver = &amp;lt;selenium.webdriver.chrome.webdriver.WebDriver (session=&amp;quot;0e271bbd02dde69fb8b1b02d84e1a18e&amp;quot;)&amp;gt;\n\n    def test_paypay_add_debit_credit_card(self, driver):\n        self.login_and_add_product_to_basket(driver)\n        check_out_page = CheckOutPage(driver)\n    \n        # calculate totals for assert\n        extract_and_calculate_totals = check_out_page.extract_and_calculate_totals(driver)\n        subtotals, shipping, totals, totals_calculated = extract_and_calculate_totals\n    \n        assert totals_calculated == totals, f&amp;quot;Total mismatch: Expected {totals_calculated}, but got {totals}&amp;quot;\n    \n        check_out_page.chose_paypal()\n        time.sleep(10)\n    \n        email_paypal = &amp;quot;sb-wwcid34547417@personal.example.com&amp;quot;\n        password_paypal = &amp;quot;KW.G0FQl&amp;quot;\n        check_out_page.login_paypal(email_paypal, password_paypal)\n        time.sleep(5)\n    \n        totals_paypal = check_out_page.get_totals_paypal()\n        assert totals_calculated == totals_paypal, &amp;quot;ok&amp;quot;\n    \n&amp;gt;       check_out_page.add_debit_credit_card_paypal()\n\nktpm\\test_payment_gateway.py:304: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages_derection\\check_out.py:535: in add_debit_credit_card_paypal\n    self.driver.find_element(By.XPATH, &amp;quot;/html/body/div[2]/div/div/div/main/div[4]/div[2]/button&amp;quot;).click()\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:748: in find_element\n    return self.execute(Command.FIND_ELEMENT, {&amp;quot;using&amp;quot;: by, &amp;quot;value&amp;quot;: value})[&amp;quot;value&amp;quot;]\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = &amp;lt;selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001E8109EF580&amp;gt;\nresponse = {&amp;#x27;status&amp;#x27;: 404, &amp;#x27;value&amp;#x27;: &amp;#x27;{&amp;quot;value&amp;quot;:{&amp;quot;error&amp;quot;:&amp;quot;no such element&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;no such element: Unable to locate element: {\\...07FF6D71DEBB9]\\\\n\\\\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\\\\n\\\\tRtlUserThreadStart [0x00007FF9B638AF38+40]\\\\n&amp;quot;}}&amp;#x27;}\n\n    def check_response(self, response: Dict[str, Any]) -&amp;gt; None:\n        &amp;quot;&amp;quot;&amp;quot;Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        &amp;quot;&amp;quot;&amp;quot;\n        status = response.get(&amp;quot;status&amp;quot;, None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(&amp;quot;message&amp;quot;, &amp;quot;&amp;quot;)\n        screen: str = response.get(&amp;quot;screen&amp;quot;, &amp;quot;&amp;quot;)\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(&amp;quot;value&amp;quot;, None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[&amp;quot;value&amp;quot;]\n                    status = value.get(&amp;quot;error&amp;quot;, None)\n                    if not status:\n                        status = value.get(&amp;quot;status&amp;quot;, ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(&amp;quot;value&amp;quot;) or value.get(&amp;quot;message&amp;quot;)\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(&amp;quot;message&amp;quot;)\n                    else:\n                        message = value.get(&amp;quot;message&amp;quot;, None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(&amp;quot;__&amp;quot;)]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[&amp;quot;value&amp;quot;]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == &amp;quot;&amp;quot; and &amp;quot;message&amp;quot; in value:\n            message = value[&amp;quot;message&amp;quot;]\n    \n        screen = None  # type: ignore[assignment]\n        if &amp;quot;screen&amp;quot; in value:\n            screen = value[&amp;quot;screen&amp;quot;]\n    \n        stacktrace = None\n        st_value = value.get(&amp;quot;stackTrace&amp;quot;) or value.get(&amp;quot;stacktrace&amp;quot;)\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(&amp;quot;\\n&amp;quot;)\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(&amp;quot;lineNumber&amp;quot;, &amp;quot;&amp;quot;)\n                        file = frame.get(&amp;quot;fileName&amp;quot;, &amp;quot;&amp;lt;anonymous&amp;gt;&amp;quot;)\n                        if line:\n                            file = f&amp;quot;{file}:{line}&amp;quot;\n                        meth = frame.get(&amp;quot;methodName&amp;quot;, &amp;quot;&amp;lt;anonymous&amp;gt;&amp;quot;)\n                        if &amp;quot;className&amp;quot; in frame:\n                            meth = f&amp;quot;{frame[&amp;#x27;className&amp;#x27;]}.{meth}&amp;quot;\n                        msg = &amp;quot;    at %s (%s)&amp;quot;\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if &amp;quot;data&amp;quot; in value:\n                alert_text = value[&amp;quot;data&amp;quot;].get(&amp;quot;text&amp;quot;)\n            elif &amp;quot;alert&amp;quot; in value:\n                alert_text = value[&amp;quot;alert&amp;quot;].get(&amp;quot;text&amp;quot;)\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n&amp;gt;       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;/html/body/div[2]/div/div/div/main/div[4]/div[2]/button&amp;quot;}\nE         (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF6D7283AF5+28005]\nE       \t(No symbol) [0x00007FF6D71E83F0]\nE       \t(No symbol) [0x00007FF6D708580A]\nE       \t(No symbol) [0x00007FF6D70D5A3E]\nE       \t(No symbol) [0x00007FF6D70D5D2C]\nE       \t(No symbol) [0x00007FF6D711EA97]\nE       \t(No symbol) [0x00007FF6D70FBA7F]\nE       \t(No symbol) [0x00007FF6D711B8B3]\nE       \t(No symbol) [0x00007FF6D70FB7E3]\nE       \t(No symbol) [0x00007FF6D70C75C8]\nE       \t(No symbol) [0x00007FF6D70C8731]\nE       \tGetHandleVerifier [0x00007FF6D757646D+3118813]\nE       \tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\nE       \tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\nE       \tGetHandleVerifier [0x00007FF6D734A44B+841403]\nE       \t(No symbol) [0x00007FF6D71F344F]\nE       \t(No symbol) [0x00007FF6D71EF4C4]\nE       \t(No symbol) [0x00007FF6D71EF65D]\nE       \t(No symbol) [0x00007FF6D71DEBB9]\nE       \tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\nE       \tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: NoSuchElementException\n\n------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongemail&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongemail&#34;, &#34;duration&#34;: &#34;00:02:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongemail&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34D90&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/25553f8d0f2ad45f5e0ac16bcccb2c73\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34310&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/25553f8d0f2ad45f5e0ac16bcccb2c73\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34970&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/25553f8d0f2ad45f5e0ac16bcccb2c73&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongnumber&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongnumber&#34;, &#34;duration&#34;: &#34;00:02:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongnumber&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CF3D0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/bd14184aff6a4a0c64c57451c2b33ac6\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CF7F0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/bd14184aff6a4a0c64c57451c2b33ac6\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CFCA0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/bd14184aff6a4a0c64c57451c2b33ac6&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongzipcode&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongzipcode&#34;, &#34;duration&#34;: &#34;00:02:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongzipcode&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34670&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/e01569a5eb50ada9e9686499ab0129d7\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34C10&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/e01569a5eb50ada9e9686499ab0129d7\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34B20&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/e01569a5eb50ada9e9686499ab0129d7&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankcity&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankcity&#34;, &#34;duration&#34;: &#34;00:02:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankcity&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CF7C0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/d03d7bc2e7ba48733abc3d15a86df758\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CFCA0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/d03d7bc2e7ba48733abc3d15a86df758\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CFB80&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/d03d7bc2e7ba48733abc3d15a86df758&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankaddress&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankaddress&#34;, &#34;duration&#34;: &#34;00:02:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankaddress&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CF2B0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/e0ca855e28e5e707704380d2fa790d71\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8100CF070&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/e0ca855e28e5e707704380d2fa790d71\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA910&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/e0ca855e28e5e707704380d2fa790d71&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blanklastname&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blanklastname&#34;, &#34;duration&#34;: &#34;00:02:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blanklastname&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34700&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/fd4c4bdb36745e395da8c649b77c36cf\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A349D0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/fd4c4bdb36745e395da8c649b77c36cf\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34C70&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/fd4c4bdb36745e395da8c649b77c36cf&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankfirstname&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankfirstname&#34;, &#34;duration&#34;: &#34;00:02:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankfirstname&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34BB0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/ef74c9268fec23c611e35f3bb5b896b8\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADAD90&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/ef74c9268fec23c611e35f3bb5b896b8\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA9A0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/ef74c9268fec23c611e35f3bb5b896b8&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankcvv&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankcvv&#34;, &#34;duration&#34;: &#34;00:02:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankcvv&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADADF0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/cb17ca491297e42fcbc09227c022d590\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA340&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/cb17ca491297e42fcbc09227c022d590\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADABE0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/cb17ca491297e42fcbc09227c022d590&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongexpirydate&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongexpirydate&#34;, &#34;duration&#34;: &#34;00:02:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongexpirydate&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34B80&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/be9bcfd89d3e053a532b91bb19fb677b\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34490&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/be9bcfd89d3e053a532b91bb19fb677b\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A341F0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/be9bcfd89d3e053a532b91bb19fb677b&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongcardnumber&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongcardnumber&#34;, &#34;duration&#34;: &#34;00:02:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_wrongcardnumber&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:02:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8109EF400&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/29c38db18d4fc34d0c3dc02aa40d0971\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8109DDB20&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/29c38db18d4fc34d0c3dc02aa40d0971\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8109DD850&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/29c38db18d4fc34d0c3dc02aa40d0971&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankallfields&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankallfields&#34;, &#34;duration&#34;: &#34;00:01:43&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_gateway_blankallfields&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:43&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_error_email&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_error_email&#34;, &#34;duration&#34;: &#34;00:01:52&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_error_email&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:52&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34C10&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/3828741177c30e5ee16e88d442173c05\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADAEE0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/3828741177c30e5ee16e88d442173c05\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA0D0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/3828741177c30e5ee16e88d442173c05&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_empty_email&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_empty_email&#34;, &#34;duration&#34;: &#34;00:01:48&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_empty_email&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:48&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA610&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/df98dd74b12cb1eae519fb2fd3e7a4e8\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADAF10&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/df98dd74b12cb1eae519fb2fd3e7a4e8\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E8109DD820&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/df98dd74b12cb1eae519fb2fd3e7a4e8&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_error_password&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_error_password&#34;, &#34;duration&#34;: &#34;00:01:53&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_error_password&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:53&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA7F0&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/99a7ee850ef3ebad2a0bfd5677b81760\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA610&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/99a7ee850ef3ebad2a0bfd5677b81760\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810ADA340&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/99a7ee850ef3ebad2a0bfd5677b81760&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_empty_password&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_empty_password&#34;, &#34;duration&#34;: &#34;00:01:59&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_payment_paypal_empty_password&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:59&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34790&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/43b50fbb57f06181711c6b9575b396a6\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34F70&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/43b50fbb57f06181711c6b9575b396a6\nWARNING  urllib3.connectionpool:connectionpool.py:827 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x000001E810A34430&amp;gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it&amp;#x27;)&amp;#x27;: /session/43b50fbb57f06181711c6b9575b396a6&#34;}], &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_wrong_when_checkout&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Failed&#34;, &#34;testId&#34;: &#34;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_wrong_when_checkout&#34;, &#34;duration&#34;: &#34;00:01:40&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Failed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_payment_gateway.py::TestPaymentGateway_Credit_or_Debit::test_paypal_wrong_when_checkout&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:40&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;self = &amp;lt;ktpm_selenium.selenium.ktpm.test_payment_gateway.TestPaymentGateway_Credit_or_Debit object at 0x000001E80FEFC4F0&amp;gt;\ndriver = &amp;lt;selenium.webdriver.chrome.webdriver.WebDriver (session=&amp;quot;bfe2756ce2fcb4e5b236d8e361a84c15&amp;quot;)&amp;gt;\n\n    def test_paypal_wrong_when_checkout(self, driver):\n        self.login_and_add_product_to_basket(driver)\n        check_out_page = CheckOutPage(driver)\n    \n        # calculate totals for assert\n        extract_and_calculate_totals = check_out_page.extract_and_calculate_totals(driver)\n        subtotals, shipping, totals, totals_calculated = extract_and_calculate_totals\n    \n        assert totals_calculated == totals, f&amp;quot;Total mismatch: Expected {totals_calculated}, but got {totals}&amp;quot;\n    \n        # Ch\u1ecdn thanh to\u00e1n b\u1eb1ng PayPal\n        check_out_page.chose_paypal()\n        time.sleep(1)\n    \n        email_paypal = &amp;quot;sb-wwcid34547417@personal.example.com&amp;quot;\n        password_paypal = &amp;quot;KW.G0FQl&amp;quot;\n        check_out_page.pay_with_paypal(email_paypal, password_paypal)\n        time.sleep(5)\n    \n        totals_paypal = check_out_page.get_totals_paypal()\n        assert totals_calculated == totals_paypal, &amp;quot;ok&amp;quot;\n    \n        # M\u00f4 ph\u1ecfng t\u00ecnh hu\u1ed1ng t\u1eaft c\u1eeda s\u1ed5 thanh to\u00e1n\n        time.sleep(5)\n        original_window = driver.window_handles[0]  # C\u1eeda s\u1ed5 g\u1ed1c\n        payment_window = driver.window_handles[1]  # C\u1eeda s\u1ed5 thanh to\u00e1n (PayPal)\n    \n        # Chuy\u1ec3n sang c\u1eeda s\u1ed5 thanh to\u00e1n\n        driver.switch_to.window(payment_window)\n        print(&amp;quot;\u0110\u00e3 chuy\u1ec3n sang c\u1eeda s\u1ed5 thanh to\u00e1n.&amp;quot;)\n    \n        # \u0110\u00f3ng c\u1eeda s\u1ed5 thanh to\u00e1n\n        driver.close()\n        print(&amp;quot;C\u1eeda s\u1ed5 thanh to\u00e1n \u0111\u00e3 b\u1ecb t\u1eaft.&amp;quot;)\n    \n        # Chuy\u1ec3n l\u1ea1i v\u1ec1 c\u1eeda s\u1ed5 g\u1ed1c\n        driver.switch_to.window(original_window)\n        print(&amp;quot;\u0110\u00e3 chuy\u1ec3n l\u1ea1i v\u1ec1 c\u1eeda s\u1ed5 g\u1ed1c.&amp;quot;)\n    \n        # Ki\u1ec3m tra tr\u1ea1ng th\u00e1i c\u1ee7a c\u1eeda s\u1ed5 g\u1ed1c\n&amp;gt;       assert &amp;quot;checkout&amp;quot; in driver.current_url\n\nktpm\\test_payment_gateway.py:849: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:444: in current_url\n    return self.execute(Command.GET_CURRENT_URL)[&amp;quot;value&amp;quot;]\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = &amp;lt;selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001E8109DD3A0&amp;gt;\nresponse = {&amp;#x27;status&amp;#x27;: 500, &amp;#x27;value&amp;#x27;: &amp;#x27;{&amp;quot;value&amp;quot;:{&amp;quot;data&amp;quot;:{&amp;quot;text&amp;quot;:&amp;quot;An order confirmation will be sent to email: sb-wwcid34547417@pers...07FF6D71DEBB9]\\\\n\\\\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\\\\n\\\\tRtlUserThreadStart [0x00007FF9B638AF38+40]\\\\n&amp;quot;}}&amp;#x27;}\n\n    def check_response(self, response: Dict[str, Any]) -&amp;gt; None:\n        &amp;quot;&amp;quot;&amp;quot;Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        &amp;quot;&amp;quot;&amp;quot;\n        status = response.get(&amp;quot;status&amp;quot;, None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(&amp;quot;message&amp;quot;, &amp;quot;&amp;quot;)\n        screen: str = response.get(&amp;quot;screen&amp;quot;, &amp;quot;&amp;quot;)\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(&amp;quot;value&amp;quot;, None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[&amp;quot;value&amp;quot;]\n                    status = value.get(&amp;quot;error&amp;quot;, None)\n                    if not status:\n                        status = value.get(&amp;quot;status&amp;quot;, ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(&amp;quot;value&amp;quot;) or value.get(&amp;quot;message&amp;quot;)\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(&amp;quot;message&amp;quot;)\n                    else:\n                        message = value.get(&amp;quot;message&amp;quot;, None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(&amp;quot;__&amp;quot;)]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[&amp;quot;value&amp;quot;]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == &amp;quot;&amp;quot; and &amp;quot;message&amp;quot; in value:\n            message = value[&amp;quot;message&amp;quot;]\n    \n        screen = None  # type: ignore[assignment]\n        if &amp;quot;screen&amp;quot; in value:\n            screen = value[&amp;quot;screen&amp;quot;]\n    \n        stacktrace = None\n        st_value = value.get(&amp;quot;stackTrace&amp;quot;) or value.get(&amp;quot;stacktrace&amp;quot;)\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(&amp;quot;\\n&amp;quot;)\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(&amp;quot;lineNumber&amp;quot;, &amp;quot;&amp;quot;)\n                        file = frame.get(&amp;quot;fileName&amp;quot;, &amp;quot;&amp;lt;anonymous&amp;gt;&amp;quot;)\n                        if line:\n                            file = f&amp;quot;{file}:{line}&amp;quot;\n                        meth = frame.get(&amp;quot;methodName&amp;quot;, &amp;quot;&amp;lt;anonymous&amp;gt;&amp;quot;)\n                        if &amp;quot;className&amp;quot; in frame:\n                            meth = f&amp;quot;{frame[&amp;#x27;className&amp;#x27;]}.{meth}&amp;quot;\n                        msg = &amp;quot;    at %s (%s)&amp;quot;\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if &amp;quot;data&amp;quot; in value:\n                alert_text = value[&amp;quot;data&amp;quot;].get(&amp;quot;text&amp;quot;)\n            elif &amp;quot;alert&amp;quot; in value:\n                alert_text = value[&amp;quot;alert&amp;quot;].get(&amp;quot;text&amp;quot;)\n&amp;gt;           raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\nE           selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: An order confirmation will be sent to email: sb-wwcid34547417@personal.example.com. Transaction ID: 33R70602T9043293M.\nE           Message: unexpected alert open: {Alert text : An order confirmation will be sent to email: sb-wwcid34547417@personal.example.com. Transaction ID: 33R70602T9043293M.}\nE             (Session info: chrome=131.0.6778.109)\nE           Stacktrace:\nE           \tGetHandleVerifier [0x00007FF6D7283AF5+28005]\nE           \t(No symbol) [0x00007FF6D71E83F0]\nE           \t(No symbol) [0x00007FF6D708580A]\nE           \t(No symbol) [0x00007FF6D711C4A2]\nE           \t(No symbol) [0x00007FF6D70FB7E3]\nE           \t(No symbol) [0x00007FF6D70C75C8]\nE           \t(No symbol) [0x00007FF6D70C8731]\nE           \tGetHandleVerifier [0x00007FF6D757646D+3118813]\nE           \tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\nE           \tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\nE           \tGetHandleVerifier [0x00007FF6D734A44B+841403]\nE           \t(No symbol) [0x00007FF6D71F344F]\nE           \t(No symbol) [0x00007FF6D71EF4C4]\nE           \t(No symbol) [0x00007FF6D71EF65D]\nE           \t(No symbol) [0x00007FF6D71DEBB9]\nE           \tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\nE           \tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nc:\\users\\admin\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:228: UnexpectedAlertPresentException\n\n------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\nDanh s\u00e1ch c\u1eeda s\u1ed5: [&amp;#x27;D0B24558BDFDC487F6ECEAC4B48A41AF&amp;#x27;, &amp;#x27;D7765671D2597593BB58FE2ACF7AF384&amp;#x27;]\nTi\u00eau \u0111\u1ec1 c\u1eeda s\u1ed5 hi\u1ec7n t\u1ea1i: Log in to your PayPal account\nPh\u1ea7n t\u1eed email input \u0111\u00e3 s\u1eb5n s\u00e0ng.\n\u0110\u00e3 nh\u1ea5n n\u00fat ti\u1ebfp t\u1ee5c.\nPh\u1ea7n t\u1eed password input \u0111\u00e3 s\u1eb5n s\u00e0ng.\n\u0110\u00e3 nh\u1ea5n n\u00fat login.\ncheckout san sang \n\u0110\u00e3 chuy\u1ec3n sang c\u1eeda s\u1ed5 thanh to\u00e1n.\nC\u1eeda s\u1ed5 thanh to\u00e1n \u0111\u00e3 b\u1ecb t\u1eaft.\n\u0110\u00e3 chuy\u1ec3n l\u1ea1i v\u1ec1 c\u1eeda s\u1ed5 g\u1ed1c.\n&#34;}], &#34;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[768-1024]&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[768-1024]&#34;, &#34;duration&#34;: &#34;00:00:09&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[768-1024]&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:09&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\nError with header display at 768x1024: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;tag name&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;header&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nError with footer display at 768x1024: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;tag name&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;footer&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\n&#34;}], &#34;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[1024-1366]&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[1024-1366]&#34;, &#34;duration&#34;: &#34;00:00:09&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[1024-1366]&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:09&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\nError at 1024x1366: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;css selector&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;.desktop-nav&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nError with header display at 1024x1366: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;tag name&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;header&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nError with footer display at 1024x1366: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;tag name&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;footer&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\n&#34;}], &#34;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[1440-900]&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[1440-900]&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;ktpm/test_responesive.py::TestResponsiveDesign::test_responsive_layout[1440-900]&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log setup ------------------------------\nWARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:138 The chromedriver version (130.0.6723.91) detected in PATH at C:\\chromedriver-win64\\chromedriver.exe might not be compatible with the detected chrome version (131.0.6778.109); currently, chromedriver 131.0.6778.87 is recommended for chrome 131.*, so it is advised to delete the driver in PATH and retry\n\n----------------------------- Captured stdout call -----------------------------\nError at 1440x900: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;css selector&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;.desktop-nav&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nError with header display at 1440x900: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;tag name&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;header&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\nError with footer display at 1440x900: Message: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;tag name&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;footer&amp;quot;}\n  (Session info: chrome=131.0.6778.109); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7283AF5+28005]\n\t(No symbol) [0x00007FF6D71E83F0]\n\t(No symbol) [0x00007FF6D708580A]\n\t(No symbol) [0x00007FF6D70D5A3E]\n\t(No symbol) [0x00007FF6D70D5D2C]\n\t(No symbol) [0x00007FF6D711EA97]\n\t(No symbol) [0x00007FF6D70FBA7F]\n\t(No symbol) [0x00007FF6D711B8B3]\n\t(No symbol) [0x00007FF6D70FB7E3]\n\t(No symbol) [0x00007FF6D70C75C8]\n\t(No symbol) [0x00007FF6D70C8731]\n\tGetHandleVerifier [0x00007FF6D757646D+3118813]\n\tGetHandleVerifier [0x00007FF6D75C6CC0+3448624]\n\tGetHandleVerifier [0x00007FF6D75BCF3D+3408301]\n\tGetHandleVerifier [0x00007FF6D734A44B+841403]\n\t(No symbol) [0x00007FF6D71F344F]\n\t(No symbol) [0x00007FF6D71EF4C4]\n\t(No symbol) [0x00007FF6D71EF65D]\n\t(No symbol) [0x00007FF6D71DEBB9]\n\tBaseThreadInitThunk [0x00007FF9B4E3259D+29]\n\tRtlUserThreadStart [0x00007FF9B638AF38+40]\n\n&#34;}]}, &#34;renderCollapsed&#34;: [&#34;passed&#34;], &#34;initialSort&#34;: &#34;result&#34;, &#34;title&#34;: &#34;report.html&#34;}"></div>
    <script>
      (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
const { getCollapsedCategory, setCollapsedIds } = require('./storage.js')

class DataManager {
    setManager(data) {
        const collapsedCategories = [...getCollapsedCategory(data.renderCollapsed)]
        const collapsedIds = []
        const tests = Object.values(data.tests).flat().map((test, index) => {
            const collapsed = collapsedCategories.includes(test.result.toLowerCase())
            const id = `test_${index}`
            if (collapsed) {
                collapsedIds.push(id)
            }
            return {
                ...test,
                id,
                collapsed,
            }
        })
        const dataBlob = { ...data, tests }
        this.data = { ...dataBlob }
        this.renderData = { ...dataBlob }
        setCollapsedIds(collapsedIds)
    }

    get allData() {
        return { ...this.data }
    }

    resetRender() {
        this.renderData = { ...this.data }
    }

    setRender(data) {
        this.renderData.tests = [...data]
    }

    toggleCollapsedItem(id) {
        this.renderData.tests = this.renderData.tests.map((test) =>
            test.id === id ? { ...test, collapsed: !test.collapsed } : test,
        )
    }

    set allCollapsed(collapsed) {
        this.renderData = { ...this.renderData, tests: [...this.renderData.tests.map((test) => (
            { ...test, collapsed }
        ))] }
    }

    get testSubset() {
        return [...this.renderData.tests]
    }

    get environment() {
        return this.renderData.environment
    }

    get initialSort() {
        return this.data.initialSort
    }
}

module.exports = {
    manager: new DataManager(),
}

},{"./storage.js":8}],2:[function(require,module,exports){
const mediaViewer = require('./mediaviewer.js')
const templateEnvRow = document.getElementById('template_environment_row')
const templateResult = document.getElementById('template_results-table__tbody')

function htmlToElements(html) {
    const temp = document.createElement('template')
    temp.innerHTML = html
    return temp.content.childNodes
}

const find = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return elem.querySelector(selector)
}

const findAll = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return [...elem.querySelectorAll(selector)]
}

const dom = {
    getStaticRow: (key, value) => {
        const envRow = templateEnvRow.content.cloneNode(true)
        const isObj = typeof value === 'object' && value !== null
        const values = isObj ? Object.keys(value).map((k) => `${k}: ${value[k]}`) : null

        const valuesElement = htmlToElements(
            values ? `<ul>${values.map((val) => `<li>${val}</li>`).join('')}<ul>` : `<div>${value}</div>`)[0]
        const td = findAll('td', envRow)
        td[0].textContent = key
        td[1].appendChild(valuesElement)

        return envRow
    },
    getResultTBody: ({ testId, id, log, extras, resultsTableRow, tableHtml, result, collapsed }) => {
        const resultBody = templateResult.content.cloneNode(true)
        resultBody.querySelector('tbody').classList.add(result.toLowerCase())
        resultBody.querySelector('tbody').id = testId
        resultBody.querySelector('.collapsible').dataset.id = id

        resultsTableRow.forEach((html) => {
            const t = document.createElement('template')
            t.innerHTML = html
            resultBody.querySelector('.collapsible').appendChild(t.content)
        })

        if (log) {
            // Wrap lines starting with "E" with span.error to color those lines red
            const wrappedLog = log.replace(/^E.*$/gm, (match) => `<span class="error">${match}</span>`)
            resultBody.querySelector('.log').innerHTML = wrappedLog
        } else {
            resultBody.querySelector('.log').remove()
        }

        if (collapsed) {
            resultBody.querySelector('.collapsible > td')?.classList.add('collapsed')
            resultBody.querySelector('.extras-row').classList.add('hidden')
        } else {
            resultBody.querySelector('.collapsible > td')?.classList.remove('collapsed')
        }

        const media = []
        extras?.forEach(({ name, format_type, content }) => {
            if (['image', 'video'].includes(format_type)) {
                media.push({ path: content, name, format_type })
            }

            if (format_type === 'html') {
                resultBody.querySelector('.extraHTML').insertAdjacentHTML('beforeend', `<div>${content}</div>`)
            }
        })
        mediaViewer.setup(resultBody, media)

        // Add custom html from the pytest_html_results_table_html hook
        tableHtml?.forEach((item) => {
            resultBody.querySelector('td[class="extra"]').insertAdjacentHTML('beforeend', item)
        })

        return resultBody
    },
}

module.exports = {
    dom,
    htmlToElements,
    find,
    findAll,
}

},{"./mediaviewer.js":6}],3:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const storageModule = require('./storage.js')

const getFilteredSubSet = (filter) =>
    manager.allData.tests.filter(({ result }) => filter.includes(result.toLowerCase()))

const doInitFilter = () => {
    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)
}

const doFilter = (type, show) => {
    if (show) {
        storageModule.showCategory(type)
    } else {
        storageModule.hideCategory(type)
    }

    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)

    const sortColumn = storageModule.getSort()
    doSort(sortColumn, true)
}

module.exports = {
    doFilter,
    doInitFilter,
}

},{"./datamanager.js":1,"./sort.js":7,"./storage.js":8}],4:[function(require,module,exports){
const { redraw, bindEvents, renderStatic } = require('./main.js')
const { doInitFilter } = require('./filter.js')
const { doInitSort } = require('./sort.js')
const { manager } = require('./datamanager.js')
const data = JSON.parse(document.getElementById('data-container').dataset.jsonblob)

function init() {
    manager.setManager(data)
    doInitFilter()
    doInitSort()
    renderStatic()
    redraw()
    bindEvents()
}

init()

},{"./datamanager.js":1,"./filter.js":3,"./main.js":5,"./sort.js":7}],5:[function(require,module,exports){
const { dom, find, findAll } = require('./dom.js')
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const { doFilter } = require('./filter.js')
const {
    getVisible,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    getSortDirection,
    possibleFilters,
} = require('./storage.js')

const removeChildren = (node) => {
    while (node.firstChild) {
        node.removeChild(node.firstChild)
    }
}

const renderStatic = () => {
    const renderEnvironmentTable = () => {
        const environment = manager.environment
        const rows = Object.keys(environment).map((key) => dom.getStaticRow(key, environment[key]))
        const table = document.getElementById('environment')
        removeChildren(table)
        rows.forEach((row) => table.appendChild(row))
    }
    renderEnvironmentTable()
}

const addItemToggleListener = (elem) => {
    elem.addEventListener('click', ({ target }) => {
        const id = target.parentElement.dataset.id
        manager.toggleCollapsedItem(id)

        const collapsedIds = getCollapsedIds()
        if (collapsedIds.includes(id)) {
            const updated = collapsedIds.filter((item) => item !== id)
            setCollapsedIds(updated)
        } else {
            collapsedIds.push(id)
            setCollapsedIds(collapsedIds)
        }
        redraw()
    })
}

const renderContent = (tests) => {
    const sortAttr = getSort(manager.initialSort)
    const sortAsc = JSON.parse(getSortDirection())
    const rows = tests.map(dom.getResultTBody)
    const table = document.getElementById('results-table')
    const tableHeader = document.getElementById('results-table-head')

    const newTable = document.createElement('table')
    newTable.id = 'results-table'

    // remove all sorting classes and set the relevant
    findAll('.sortable', tableHeader).forEach((elem) => elem.classList.remove('asc', 'desc'))
    tableHeader.querySelector(`.sortable[data-column-type="${sortAttr}"]`)?.classList.add(sortAsc ? 'desc' : 'asc')
    newTable.appendChild(tableHeader)

    if (!rows.length) {
        const emptyTable = document.getElementById('template_results-table__body--empty').content.cloneNode(true)
        newTable.appendChild(emptyTable)
    } else {
        rows.forEach((row) => {
            if (!!row) {
                findAll('.collapsible td:not(.col-links', row).forEach(addItemToggleListener)
                find('.logexpander', row).addEventListener('click',
                    (evt) => evt.target.parentNode.classList.toggle('expanded'),
                )
                newTable.appendChild(row)
            }
        })
    }

    table.replaceWith(newTable)
}

const renderDerived = () => {
    const currentFilter = getVisible()
    possibleFilters.forEach((result) => {
        const input = document.querySelector(`input[data-test-result="${result}"]`)
        input.checked = currentFilter.includes(result)
    })
}

const bindEvents = () => {
    const filterColumn = (evt) => {
        const { target: element } = evt
        const { testResult } = element.dataset

        doFilter(testResult, element.checked)
        const collapsedIds = getCollapsedIds()
        const updated = manager.renderData.tests.map((test) => {
            return {
                ...test,
                collapsed: collapsedIds.includes(test.id),
            }
        })
        manager.setRender(updated)
        redraw()
    }

    const header = document.getElementById('environment-header')
    header.addEventListener('click', () => {
        const table = document.getElementById('environment')
        table.classList.toggle('hidden')
        header.classList.toggle('collapsed')
    })

    findAll('input[name="filter_checkbox"]').forEach((elem) => {
        elem.addEventListener('click', filterColumn)
    })

    findAll('.sortable').forEach((elem) => {
        elem.addEventListener('click', (evt) => {
            const { target: element } = evt
            const { columnType } = element.dataset
            doSort(columnType)
            redraw()
        })
    })

    document.getElementById('show_all_details').addEventListener('click', () => {
        manager.allCollapsed = false
        setCollapsedIds([])
        redraw()
    })
    document.getElementById('hide_all_details').addEventListener('click', () => {
        manager.allCollapsed = true
        const allIds = manager.renderData.tests.map((test) => test.id)
        setCollapsedIds(allIds)
        redraw()
    })
}

const redraw = () => {
    const { testSubset } = manager

    renderContent(testSubset)
    renderDerived()
}

module.exports = {
    redraw,
    bindEvents,
    renderStatic,
}

},{"./datamanager.js":1,"./dom.js":2,"./filter.js":3,"./sort.js":7,"./storage.js":8}],6:[function(require,module,exports){
class MediaViewer {
    constructor(assets) {
        this.assets = assets
        this.index = 0
    }

    nextActive() {
        this.index = this.index === this.assets.length - 1 ? 0 : this.index + 1
        return [this.activeFile, this.index]
    }

    prevActive() {
        this.index = this.index === 0 ? this.assets.length - 1 : this.index -1
        return [this.activeFile, this.index]
    }

    get currentIndex() {
        return this.index
    }

    get activeFile() {
        return this.assets[this.index]
    }
}


const setup = (resultBody, assets) => {
    if (!assets.length) {
        resultBody.querySelector('.media').classList.add('hidden')
        return
    }

    const mediaViewer = new MediaViewer(assets)
    const container = resultBody.querySelector('.media-container')
    const leftArrow = resultBody.querySelector('.media-container__nav--left')
    const rightArrow = resultBody.querySelector('.media-container__nav--right')
    const mediaName = resultBody.querySelector('.media__name')
    const counter = resultBody.querySelector('.media__counter')
    const imageEl = resultBody.querySelector('img')
    const sourceEl = resultBody.querySelector('source')
    const videoEl = resultBody.querySelector('video')

    const setImg = (media, index) => {
        if (media?.format_type === 'image') {
            imageEl.src = media.path

            imageEl.classList.remove('hidden')
            videoEl.classList.add('hidden')
        } else if (media?.format_type === 'video') {
            sourceEl.src = media.path

            videoEl.classList.remove('hidden')
            imageEl.classList.add('hidden')
        }

        mediaName.innerText = media?.name
        counter.innerText = `${index + 1} / ${assets.length}`
    }
    setImg(mediaViewer.activeFile, mediaViewer.currentIndex)

    const moveLeft = () => {
        const [media, index] = mediaViewer.prevActive()
        setImg(media, index)
    }
    const doRight = () => {
        const [media, index] = mediaViewer.nextActive()
        setImg(media, index)
    }
    const openImg = () => {
        window.open(mediaViewer.activeFile.path, '_blank')
    }
    if (assets.length === 1) {
        container.classList.add('media-container--fullscreen')
    } else {
        leftArrow.addEventListener('click', moveLeft)
        rightArrow.addEventListener('click', doRight)
    }
    imageEl.addEventListener('click', openImg)
}

module.exports = {
    setup,
}

},{}],7:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const storageModule = require('./storage.js')

const genericSort = (list, key, ascending, customOrder) => {
    let sorted
    if (customOrder) {
        sorted = list.sort((a, b) => {
            const aValue = a.result.toLowerCase()
            const bValue = b.result.toLowerCase()

            const aIndex = customOrder.findIndex((item) => item.toLowerCase() === aValue)
            const bIndex = customOrder.findIndex((item) => item.toLowerCase() === bValue)

            // Compare the indices to determine the sort order
            return aIndex - bIndex
        })
    } else {
        sorted = list.sort((a, b) => a[key] === b[key] ? 0 : a[key] > b[key] ? 1 : -1)
    }

    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const durationSort = (list, ascending) => {
    const parseDuration = (duration) => {
        if (duration.includes(':')) {
            // If it's in the format "HH:mm:ss"
            const [hours, minutes, seconds] = duration.split(':').map(Number)
            return (hours * 3600 + minutes * 60 + seconds) * 1000
        } else {
            // If it's in the format "nnn ms"
            return parseInt(duration)
        }
    }
    const sorted = list.sort((a, b) => parseDuration(a['duration']) - parseDuration(b['duration']))
    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const doInitSort = () => {
    const type = storageModule.getSort(manager.initialSort)
    const ascending = storageModule.getSortDirection()
    const list = manager.testSubset
    const initialOrder = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed', 'Skipped', 'Passed']

    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    if (type?.toLowerCase() === 'original') {
        manager.setRender(list)
    } else {
        let sortedList
        switch (type) {
        case 'duration':
            sortedList = durationSort(list, ascending)
            break
        case 'result':
            sortedList = genericSort(list, type, ascending, initialOrder)
            break
        default:
            sortedList = genericSort(list, type, ascending)
            break
        }
        manager.setRender(sortedList)
    }
}

const doSort = (type, skipDirection) => {
    const newSortType = storageModule.getSort(manager.initialSort) !== type
    const currentAsc = storageModule.getSortDirection()
    let ascending
    if (skipDirection) {
        ascending = currentAsc
    } else {
        ascending = newSortType ? false : !currentAsc
    }
    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    const list = manager.testSubset
    const sortedList = type === 'duration' ? durationSort(list, ascending) : genericSort(list, type, ascending)
    manager.setRender(sortedList)
}

module.exports = {
    doInitSort,
    doSort,
}

},{"./datamanager.js":1,"./storage.js":8}],8:[function(require,module,exports){
const possibleFilters = [
    'passed',
    'skipped',
    'failed',
    'error',
    'xfailed',
    'xpassed',
    'rerun',
]

const getVisible = () => {
    const url = new URL(window.location.href)
    const settings = new URLSearchParams(url.search).get('visible')
    const lower = (item) => {
        const lowerItem = item.toLowerCase()
        if (possibleFilters.includes(lowerItem)) {
            return lowerItem
        }
        return null
    }
    return settings === null ?
        possibleFilters :
        [...new Set(settings?.split(',').map(lower).filter((item) => item))]
}

const hideCategory = (categoryToHide) => {
    const url = new URL(window.location.href)
    const visibleParams = new URLSearchParams(url.search).get('visible')
    const currentVisible = visibleParams ? visibleParams.split(',') : [...possibleFilters]
    const settings = [...new Set(currentVisible)].filter((f) => f !== categoryToHide).join(',')

    url.searchParams.set('visible', settings)
    window.history.pushState({}, null, unescape(url.href))
}

const showCategory = (categoryToShow) => {
    if (typeof window === 'undefined') {
        return
    }
    const url = new URL(window.location.href)
    const currentVisible = new URLSearchParams(url.search).get('visible')?.split(',').filter(Boolean) ||
        [...possibleFilters]
    const settings = [...new Set([categoryToShow, ...currentVisible])]
    const noFilter = possibleFilters.length === settings.length || !settings.length

    noFilter ? url.searchParams.delete('visible') : url.searchParams.set('visible', settings.join(','))
    window.history.pushState({}, null, unescape(url.href))
}

const getSort = (initialSort) => {
    const url = new URL(window.location.href)
    let sort = new URLSearchParams(url.search).get('sort')
    if (!sort) {
        sort = initialSort || 'result'
    }
    return sort
}

const setSort = (type) => {
    const url = new URL(window.location.href)
    url.searchParams.set('sort', type)
    window.history.pushState({}, null, unescape(url.href))
}

const getCollapsedCategory = (renderCollapsed) => {
    let categories
    if (typeof window !== 'undefined') {
        const url = new URL(window.location.href)
        const collapsedItems = new URLSearchParams(url.search).get('collapsed')
        switch (true) {
        case !renderCollapsed && collapsedItems === null:
            categories = ['passed']
            break
        case collapsedItems?.length === 0 || /^["']{2}$/.test(collapsedItems):
            categories = []
            break
        case /^all$/.test(collapsedItems) || collapsedItems === null && /^all$/.test(renderCollapsed):
            categories = [...possibleFilters]
            break
        default:
            categories = collapsedItems?.split(',').map((item) => item.toLowerCase()) || renderCollapsed
            break
        }
    } else {
        categories = []
    }
    return categories
}

const getSortDirection = () => JSON.parse(sessionStorage.getItem('sortAsc')) || false
const setSortDirection = (ascending) => sessionStorage.setItem('sortAsc', ascending)

const getCollapsedIds = () => JSON.parse(sessionStorage.getItem('collapsedIds')) || []
const setCollapsedIds = (list) => sessionStorage.setItem('collapsedIds', JSON.stringify(list))

module.exports = {
    getVisible,
    hideCategory,
    showCategory,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    setSort,
    getSortDirection,
    setSortDirection,
    getCollapsedCategory,
    possibleFilters,
}

},{}]},{},[4]);
    </script>
  </footer>
</html>